services:
  ai_delver:
    build: .
    image: ai_delver
    container_name: ai_delver
    working_dir: /app
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=~/.Xauthority
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/app
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    entrypoint: python3
    command: src/main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
