services:
  ai_delver_ai:
    ports:
      - "8001:8001"
    build:
      context: .
      dockerfile: ai_delver_intelligence/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: ai_delver_intelligence
    container_name: ai_delver_intelligence
    working_dir: /app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_REQUIRE_CUDA=cuda>=11.8
    volumes:
      - ./ai_delver_intelligence:/app
      - ./pytiling-lib:/app/pytiling-lib
      - ./pyglet-dragonbones:/app/pyglet-dragonbones
      - ./ai_delver_runtime:/app/ai_delver_runtime
      - ./level-lib:/app/level-lib
      - ./assets:/app/assets
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["python3", "src/main.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
